# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cmnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Author')),
                ('comnt_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='cmnt',
            name='author',
        ),
        migrations.DeleteModel(
            name='Cmnt',
        ),
    ]
