# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170804_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comnt',
            name='my_date_field',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comnt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comnt',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comnt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
